name: Scraping CENACE demanda

on:
  schedule:
    - cron: '0,30 * * * *'  # Ejecuta cada media hora
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run scraping script
      run: python scraping_demanda.py

    - name: Configure git for push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add demanda_log.csv
        # Solo hace commit si hay cambios
        git diff --cached --quiet || git commit -m "Actualizaci칩n autom치tica de demanda"
        git push
      env:
        # TOKEN autom치tico para permitir push sin problemas
        # Este token ya est치 disponible en GitHub Actions en 'secrets.GITHUB_TOKEN'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
