name: Scraping CENACE demanda

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora, en minuto 0 (UTC)
  workflow_dispatch:       # Permite ejecutar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install chromium

    - name: Run scraping script
      run: python scraping_demanda.py

    - name: Configure Git for pushing changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add demanda_log.csv
        git commit -m "Actualiza demanda_log.csv con dato y hora" || echo "No hay cambios para hacer commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
